# Pipeline pour un projet Python avec Github Actions

name: Python CI
on: [push]

# Contrainte de temps de build
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    # Installation de Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    # Installation des dépendances
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Validation de la qualité du code
    - name: Lint with pylint
      run: |
        pip install pylint
        pylint functions.py

    # Exécution des tests
    - name: Test with pytest
      run: |
        pip install pytest
        pytest

    # Envoi de la notification par mail 
    - name: Send email notification
      uses: dawidd6/action-send-mail@v3.1.0
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: 'Python CI/CD Pipeline Result'
        body: 'The Python CI/CD pipeline has completed. Please check the pipeline results.'
        to: hananetest9@gmail.com
